using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Fux.Pratt
{
    /// <summary>
    /// A simple token class. These are generated by <see cref="LexerOriginal"/>
    /// and consumed by <see cref="ParserOriginal"/>.
    /// </summary>
    public sealed class TokenOriginal
    {
        public TokenOriginal(TokenType type, string text)
        {
            Type = type;
            Text = text;
        }

        public TokenType Type
        {
            get;
        }

        public string Text
        {
            get;
        }

        public override string ToString() { return Text; }
    }
}
