language: node_js
node_js:
  - '12'
script: make ci-test

before_deploy:
  - echo $RC >> .npmrc

deploy:
  - provider: script
    skip_cleanup: true
    script: npm run release
    on:
      branch: master

  - provider: script
    skip_cleanup: true
    script: npm run release
    on:
      tags: true

env:
  global:
    secure: KeanNBCLPLjle0fFvksbC5u9jbRMy8cN8XLUAtcaTqaXAc2mqcWyijKU2Sy3P1SF5lZPYDE9inX8oGRQFAoEr2PaiOxNjBpKBndIoPa1LgDSIkc2zDV2dLeCrrvbLNPgEuc2UegO71j14jNJOOmFkPBYOWgP7abynnsh75+No/GQmvscPtXnq18Koldg2bdlh/odFGNtUxKUqDVzKtmZ9RHMQ4lp+HTMI0qoFsJn64WExK35pdeBYpPvzc6rj1uJJD3b0ssL6ZXJ3Ky097Eou0jf6IPv0mL9d7EC4n2yOj7WHcTX4oKwt8gTNI7gUTU+Qo/H/PBPhjlf/hfE8kzxSFkqLq3ybn+xwf6KUB794tKl9OlLOQ80LCl4aaVwdC2fxd3TZBmD2SyZV+2wuehOQtf2xor6cGb9Z1wLtNFoHqbfCc1eUTWPM4yr86ehuw3PIic2p+wYtHVHaKG8fWlljl1NtFoLax8vCpAEZ5Uq0ypZV5PSqNKiTbKNx79mRcFwO+JXS2VAzxTqvlRq147n0DbiKRnVwsvjFriXWuKWmm8hqIo4mNrbrPI6HVKJarUYftqWyrMBsof2Muv5XUteSQmR/s6IxwECAmm6HnA7Nm5km/pIC+Bn1a64HEjyM7V0JRFuaJQhwws7SnsNyTjUwAdUvcSbtj+vJm6CMQ/rVco=
